### PR TITLE
Add link to raw FLR/SLR

### PR DESCRIPTION
**Pull request by comex**

### CODE REVIEW

**Review by PubliusScriboniusScholasticus — APPROVED** [review]

**Comment by Gaelan** [comment]
Thanks! This looks good, though in the future I'd appreciate you checking with me (it is my report after all, and I'm the one that gets carded if something goes wrong).

**Comment by PubliusScriboniusScholasticus** [comment]
Yes, I by no means intended to stop your input by approving it. Also, I
believe since this was only the HLR, it has no game standing and therefore
could not have led to a card.

**Comment by Gaelan** [comment]
True. Maybe this is me being a control freak, but I'd still appreciate letting me merge it—I'm usually pretty quick to see this sort of thing.

**Comment by PubliusScriboniusScholasticus** [comment]
I completely understand and want to make it clear that I had no intention
to imply otherwise.

**Comment by comex** [comment]
Sorry - honestly I forgot who the Rulekeepor was (still getting to know the
newer players), and figured that if Publius approved it then he was in
charge. 😥

**Pull request merged**
